version: '2'
services: 
  hub:
    image: selenium/hub:3.11.0
    ports:
      - "4444:4444"
    environment:
      SE_OPTS: -timeout 30000 -browserTimeout 30000 # Keep stuff running

  chrome:
    image: selenium/node-firefox-debug:3.11.0
    shm_size: 2048M
    ports:
      - "5900"
    depends_on:
      - hub
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444